#!/bin/bash

echo "Running pre-push tests..."

go test -v /redis/cmd # ??

if [ $? -ne 0 ]; then
    echo "Tests failed! Aborting push."
    exit 1
fi

echo "Tests passed! Proceeding with push."
exit 0